name: Test 518

on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      DOTNET_INSTALL_DIR: ''
      DOTNET_ROOT: ''

    steps:
      - uses: actions/checkout@main

      - name: Setup .NET
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: '8.0.x'
      
      - name: Verify .NET installation
        run: |
          dotnet --version
          dotnet --list-sdks
          dotnet --list-runtimes
          echo "${{ which dotnet }}"
  

  test-4:
    name: ${{ matrix.os }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      DOTNET_INSTALL_DIR: ''
      DOTNET_ROOT: ''

    steps:
      - uses: actions/checkout@main

      - name: Setup .NET
        uses: v-mahabaleshwars/setup-dotnet@feature/518-fallback
        with:
          dotnet-version: '8.0.x'
      
      - name: Verify .NET installation
        run: |
          dotnet --version
          dotnet --list-sdks
          dotnet --list-runtimes
          echo "${{ which dotnet }}"

  test-5:
    name: ${{ matrix.os }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      DOTNET_INSTALL_DIR: ''
      DOTNET_ROOT: ''

    steps:
      - uses: actions/checkout@main

      - name: Setup .NET
        uses: v-priyagupta108/setup-dotnet@install-dir-writable-fallback
        with:
          dotnet-version: '8.0.x'
      
      - name: Verify .NET installation
        run: |
          dotnet --version
          dotnet --list-sdks
          dotnet --list-runtimes
          echo "${{ which dotnet }}"